= Gradle-AsciidoctorJ README
Jnorthr <james.b.northrop@googlemail.com>
v0.5, 2021-12-25
:icons: font
:toc: left
:imagesdir: images
:sectlinks:
:sectnums:

== Status

*Travis C/I* Project Health -
image:https://img.shields.io/travis/jnorthr/gradle-asciidoctorj.svg[Build Status (Travis CI), link=https://travis-ci.com/jnorthr/gradle-asciidoctorj]  image:https://img.shields.io/hexpm/l/plug.svg[Apache License, link=https://github.com/jnorthr/gradle-asciidoctorj/blob/master/LICENSE]


A skeleton project for documentation users of asciidoc files. These text files can be turned into other styles of product, like *html*, *PDF* and more. See their website https://asciidoctor.org[asciidoctor.org] for more details and a review of the *asciidoc* syntax. 

== Purpose

This version of this tool will examine files found within a single input folder location. For each input file whose name ends with the *.adoc* suffix, this tool will translate the document into an internet-useful *.html* file format. These translated files are written into an output directory folder. 

As this tool uses the *Gradle* build application, a script text file named *build.gradle* directs Gradle. Within that script are two folder declarations. These declarations look similar to this :

.Folder Locations
----
    sourceDir = new File("src/main/resources")
    outputDir = new File("$buildDir/docs")
----   

The *sourceDir* declaration identifies the folder location where all your text documents reside and are taken from. The *outputDir* declaration is where this tool will write your *.html* results for each input file. You can adjust or change these values to suit your strategy for document pipeline production. 

== Structure

This clone includes gradle build tool wrapper and folder structure like maven/gradle

== Pre-requisites

 . Working internet connection
 . Installed Git client to copy/clone this repo
 . Ability to use terminal console

== Steps

 . open terminal console

 . change directory ( cd ) into target folder location

 . run this command to create a folder named gradle-asciidoctorj and copy down all the pieces :

	`git clone https://github.com/jnorthr/gradle-asciidoctorj.git`

 . *cd gradle-asciidoctorj*

 . *./gradlew*

 . after step 4 completes, examine *gradle-asciidoctorj* folder to find the */build/docs* folder with an html file for each asciidoctor file in the */resources* folder 

''''

TIP:  Have added a gradle task called *copyImages* to copy image files from the *./images* file into *$buildDir/docs/images*
